#!/usr/bin/php
<?php

// Standard includes

$our_include_path=dirname(__FILE__) . ":" . dirname(__FILE__) . "/../common" . ":" . GETENV("HOME");
set_include_path($our_include_path);
require "get-directories.php";


// If a cached result is available, use it instead

$max_age_seconds=5*60; // 5 minutes
try_cache($cache_file, $max_age_seconds);


// Retrieve the JSON results

$api_url="http://api.open-notify.org/iss-pass.json?lat=38.939626&lon=-76.990228&n=1&alt=60";

while (!$parsed_json && $errors<3) {
	$json_string = file_get_contents($api_url);
	$parsed_json = json_decode($json_string);
	if (!$parsed_json) {
		$errors++;
		sleep(2);
	}
}

if ($errors>=3) {
	exit;
}


// Parse the JSON results

$risetime = $parsed_json->{'response'}[0]->{'risetime'};
$duration = $parsed_json->{'response'}[0]->{'duration'};


// Send 

send_to_client("s" . $risetime . " " . $duration);


?>