#!/usr/bin/php
<?php
$our_include_path=dirname(__FILE__) . ":" . dirname(__FILE__) . "/../common" . ":" . GETENV("HOME");
set_include_path($our_include_path);
require "get-directories.php";
echo $our_include_path . "\n";
echo $base_dir . "\n";

$max_age=30*60; // 30 minutes

try_cache($cache_file, $max_age);


?>