#!/usr/bin/php
<?php
	date_default_timezone_set('America/New_York');
	ini_set('default_socket_timeout', 15);

$parsed_json_conditions=null;
$parsed_json_forecast=null;
$errors=0;

while (!$parsed_string_conditions && $errors<5) {

	$json_string_conditions = file_get_contents("http://api.wunderground.com/api/90eba8f2b040b290/geolookup/conditions/q/DC/Washington.json");
  $parsed_json_conditions = json_decode($json_string_conditions);
	if (!$parsed_json_conditions) {
$errors++;
sleep(2);
}

}


  $location = $parsed_json_conditions->{'location'}->{'city'};
  $temp_f = $parsed_json_conditions->{'current_observation'}->{'temp_f'};
  
  
while (!$parsed_string_forecast && $errors<5) {
$json_string_forecast = file_get_contents("http://api.wunderground.com/api/90eba8f2b040b290/geolookup/forecast/q/DC/Washington.json");
  $parsed_json_forecast = json_decode($json_string_forecast);
	if (!$parsed_json_forecast) {
$errors++;
sleep(2);
}

  }

$this_forecast = $parsed_json_forecast->{'forecast'}->{'simpleforecast'}->{'forecastday'}[0];


$temp_low = $this_forecast->{'low'}->{'fahrenheit'};
$temp_high = $this_forecast->{'high'}->{'fahrenheit'};
$humidity = $this_forecast->{'avehumidity'};
$rain_inches = $this_forecast->{'qpf_allday'}->{'in'};
$precip_chance = $this_forecast->{'pop'};
$snow_inches = $this_forecast->{'snow_allday'}->{'in'};
$conditions = $this_forecast->{'conditions'};

echo "WCLKKBASES0" . round($temp_f) . chr(223) . " now. " . $temp_low . "-" . $temp_high . chr(223) . "\n";

usleep(50000);


if ($snow_inches > 0 ) {
echo "WCLKKBASES1" . round($snow_inches,1) . '" SNOW! (' . $precip_chance . "%)" . "\n";
	
	
} else if ($rain_inches > 0 ) {
	
echo "WCLKKBASES1" . round($rain_inches,1) . '" rain (' . $precip_chance . "%)" . "\n";

} else if ($humidity > 60)  {

echo "WCLKKBASES1" . round($humidity) . "% humidity" . "\n";
} else {
	
echo "WCLKKBASES1" . ucfirst(strtolower(trim($conditions))) . "\n";

}


