#!/usr/bin/php
<?php
/**
 * OpenWeatherMap-PHP-API — A php api to parse weather data from http://www.OpenWeatherMap.org .
 *
 * @license MIT
 *
 * Please see the LICENSE file distributed with this source code for further
 * information regarding copyright and licensing.
 *
 * Please visit the following links to read about the usage policies and the license of
 * OpenWeatherMap before using this class:
 *
 * @see http://www.OpenWeatherMap.org
 * @see http://www.OpenWeatherMap.org/about
 * @see http://www.OpenWeatherMap.org/copyright
 * @see http://openweathermap.org/appid
 */

use Cmfcmf\OpenWeatherMap;

if (file_exists(realpath(dirname(__FILE__)) . '/vendor/autoload.php')) {
    // Library is not part of a project. "composer install" was executed directly on this library's composer file.
    require(realpath(dirname(__FILE__)) . '/vendor/autoload.php');
} else {
    // Library is part of a project.
    /** @noinspection PhpIncludeInspection */
    require('../../../autoload.php');
}

// Language of data (try your own language here!):
$lang = 'en';

// Units (can be 'metric' or 'imperial' [default]):
$units = 'imperial';

// Get OpenWeatherMap object. Don't use caching (take a look into Example_Cache.php to see how it works).
$owm = new OpenWeatherMap();

// Example 1: Get forecast for the next 10 days for 4140963.

$forecast = $owm->getWeatherForecast('4140963', $units, $lang, '', 1);

$weather = $owm->getWeather('4140963', $units, $lang);


$min=round($weather->temperature->getValue());
$max=round($weather->temperature->getValue());
$precip=intval($weather->precipitation->getValue());
$preciptext=$weather->precipitation->getDescription();
$cloud=intval($weather->clouds->getValue());
$cloudtext=$weather->clouds->getDescription();


foreach ($forecast as $thisweather) {
	if (round($thisweather->temperature->getValue())<$min) {
	$min = round($thisweather->temperature->getValue());
} 
if (round($thisweather->temperature->getValue())>$max) {
$max = round($thisweather->temperature->getValue());
}    
	if ( (intval($thisweather->precipitation->getValue() ) > $precip)) {

		$precip=(intval($thisweather->precipitation->getValue() ));
		$preciptext=$thisweather->precipitation->getDescription();
	}
	if ( (intval($thisweather->clouds->getValue() ) > $cloud)) {

		$cloud=(intval($thisweather->clouds->getValue() ));
		$cloudtext=$thisweather->clouds->getDescription();
	}
	
}


echo "WCLKKBASES0" . round($weather->temperature->getValue()) . chr(223) . " now; " . $min . "-" . $max . "\n";
usleep(50000);


if ($precip > 0) {

echo "WCLKKBASES1" . ucfirst($preciptext) . " (" . $precip . ")\n";

} else {

echo "WCLKKBASES1" . ucfirst($cloudtext) . "\n";

}

# . $weather->description . "\n";


