#!/usr/bin/php
<?php
	date_default_timezone_set('America/New_York');

$json_string_conditions = file_get_contents("http://api.wunderground.com/api/90eba8f2b040b290/geolookup/conditions/q/DC/Washington.json");
  $parsed_json_conditions = json_decode($json_string_conditions);
  $location = $parsed_json_conditions->{'location'}->{'city'};
  $temp_f = $parsed_json_conditions->{'current_observation'}->{'temp_f'};
  
  
$json_string_forecast = file_get_contents("http://api.wunderground.com/api/90eba8f2b040b290/geolookup/forecast/q/DC/Washington.json");
  $parsed_json_forecast = json_decode($json_string_forecast);
  
$this_forecast = $parsed_json_forecast->{'forecast'}->{'simpleforecast'}->{'forecastday'}[0];


$temp_low = $this_forecast->{'low'}->{'fahrenheit'};
$temp_high = $this_forecast->{'high'}->{'fahrenheit'};
$humidity = $this_forecast->{'avehumidity'};
$rain_inches = $this_forecast->{'qpf_allday'}->{'in'};
$precip_chance = $this_forecast->{'pop'};
$snow_inches = $this_forecast->{'snow_allday'}->{'in'};
$conditions = $this_forecast->{'conditions'};

echo "WCLKKBASES0" . round($temp_f) . chr(223) . " now; " . $temp_low . "-" . $temp_high . "\n";

usleep(50000);


if ($snow_inches > 0 ) {
echo "WCLKKBASES1" . $snow_inches . "in SNOW! (" . $precip_chance . "%)" . "\n";
	
	
} else if ($rain_inches > 0 ) {
	
echo "WCLKKBASES1" . $rain_inches . "in rain (" . $precip_chance . "%)" . "\n";

} else if ($humidity > 60)  {

echo "WCLKKBASES1" . $humidity . "% humidity" . "\n";
} else {
	
echo "WCLKKBASES1" . ucfirst(strtolower(trim($conditions))) . "\n";

}


