#!/bin/bash

cd `dirname $0`
. ../common/get-directories

# curl 'http://interactive.guim.co.uk/2015/the-counted/v/1460319534281/js/main.js' 2>/dev/null | grep 'var total$1' | sed -e 's:.* = ::' -e 's:;.*::' -e 's:^:V:' -e "s:^:$FROM$BASE:"
curl http://killedbypolice.net/ 2>/dev/null | grep '<center>(' | head -1 | sed -e "s:.*[(]::" -e "s:[)].*::" -e "s:^:$FROM$BASE:"
echo ""
