#!/bin/bash
cd `dirname $0`
. ../common/get-directories

# First argument is moved to FROM by get-directories
NEWNAME="$FROM" 
PREFIX="FRESH$BASE"
SETBASE="\$B"
SETCLIENT="\$C"

if [ "$NEWNAME" = "" ]
then
	echo "Usage: $0 [new-name]"
	exit 1
else
	echo "$PREFIX$SETBASE$BASE" > $BASEDIR/out/provision1
	sleep 3
	echo "$PREFIX$SETCLIENT$NEWNAME" > $BASEDIR/out/provision2 
	exit 0
fi