#!/bin/bash
cd `dirname $0`
. ../common/get-directories

	if [ "$FROM" != "" ] 
		then
		TEMP=`mktemp /tmp/nrf24.XXXXX`
		ZONES=`find $BASE/zones/ -name "$FROM" | sed -e 's:/[^/]*$::' `
		
		for ZONE in $ZONES
			do 
			
			ZONENAME=`dirname "$ZONE"`
			if [ -d "$ZONENAME" ] 
				then
					touch "$ZONENAME/last-seen"
			fi
					
			if [ "$ZONE" != "" ] 
				then
					find "$ZONE" -maxdepth 1 -mindepth 1 -type f | sed -e 's:.*/::' >> $TEMP
			fi
		done
		CLIENTS=`cat $TEMP|sort|uniq`
		for CLIENT in $CLIENTS
		do		
			if [ "$CLIENT" != "" ] 
				then	
				
				if [ -x "../$CLIENT/zone-sense" ]
					then
					../$CLIENT/zone-sense $FROM $DETAILS & 
				elif [ -x "../$CLIENT/update" ]
					then
					../$CLIENT/update $FROM $DETAILS & 
				fi
			fi
		done
		
		rm $TEMP

	fi

wait

