#!/bin/bash

cd "$( dirname "${BASH_SOURCE[0]}" )"

. ../common/get-directories

KEY=`cat .api-key | tr \n ' ' | sed -e 's: ::g'`
echo -n $FROM
echo -n $BASE
echo -n "0H8 MtP: "

curl -s "http://api.wmata.com/NextBusService.svc/Predictions?StopID=1001919&api_key=$KEY&subscription_key=$KEY" | sed -e 's:<:\n<:g' |  grep Minutes | sed -e 's:<[/]*Minutes>::g' | head -5 | tr '\n' ','|sed -e 's:,:, :g' -e 's:, , :, :g' -e 's:, , :, :g' -e 's:, $::' -e 's:, :,:g'
echo -ne "\n"
sleep 0.1

echo -n $FROM
echo -n $BASE
echo -n "1H8 RIA: "
curl -s "http://api.wmata.com/NextBusService.svc/Predictions?StopID=1001925&api_key=$KEY&subscription_key=$KEY" | sed -e 's:<:\n<:g' |  grep Minutes | sed -e 's:<[/]*Minutes>::g' | head -5 | tr '\n' ','|sed -e 's:,:, :g' -e 's:, , :, :g' -e 's:, , :, :g' -e 's:, $::' -e 's:, :,:g'
echo -ne "\n"
