#!/usr/bin/php
<?php

// Standard includes

$our_include_path=dirname(__FILE__) . ":" . dirname(__FILE__) . "/../common" . ":" . GETENV("HOME");
set_include_path($our_include_path);
require "get-directories.php";


// Per-project includes


// Try to use cached results first

$max_age_seconds=60*30;
try_cache($cache_file,$max_age_seconds);


// Ugly curl one-liner

$doc = new DOMXPath(@DOMDocument::loadHTML(file_get_contents("https://killedbypolice.net/")));

$num = 0;
foreach($doc->query("//h3") as $el){
	$val = $el->nodeValue;
	if (strpos($val, "pdated") > -1) {
		$arr = explode(" ",$val);
		$num = $arr[0];
	}
}


send_to_client("V" . $num);

?>
