#!/bin/bash
cd `dirname $0`
. ../common/get-directories

# SECONDS=`date +%s`
# SECONDS=`node -e 'console.log( Math.round(new Date().getTime()/1000.0) - new Date().getTimezoneOffset()*60);'`
SECONDS=`nodejs -e 'console.log( Math.round(new Date().getTime()/1000.0) - new Date().getTimezoneOffset()*60);'`

# TODO: fallback

echo -n $FROM;echo -n $BASE;echo t$SECONDS\|$SECONDS
