#!/usr/bin/php
<?php
chdir(dirname(__FILE));

date_default_timezone_set('America/New_York');
ini_set('default_socket_timeout', 15);
$parsed_json=null;
$errors=0;
$max_age=60*30;
$cache_file="/tmp/cache-mirf-GIPHY";
$cache_dir="/tmp/cache-mirf-GIPHY-files/";


while (!$parsed_json && $errors<2) {

 

$json_string_newgif = file_get_contents("http://api.giphy.com/v1/gifs/random?api_key=dc6zaTOxFJmzC");
  
$parsed_json = json_decode($json_string_newgif);

	if (!$parsed_json) {
		$errors++;
		sleep(2);
	}
  }

if (!file_exists($cache_dir)) {
	mkdir($cache_dir, 0755);
}

$this_gif = $parsed_json->{'data'}->{'image_url'};
$this_gif_tags = $parsed_json->{'data'}->{'tags'};
$this_gif_tag = end($this_gif_tags);

$this_gif_id = $parsed_json->{'data'}->{'id'};
$this_gif_id_short = substr($this_gif_id,-6);

$gif = file_get_contents($this_gif);
file_put_contents($cache_dir . $this_gif_id_short . ".gif",$gif);
file_put_contents($cache_dir . $this_gif_id_short . ".txt",$this_gif_tag);
$output = shell_exec("./gif2bmps.sh '" . $cache_dir . $this_gif_id_short . ".gif' '" . $cache_dir . $this_gif_id_short . "'");
$output = shell_exec("./bmps2raw.sh '" . $cache_dir . $this_gif_id_short . "'");


?>
