#!/usr/bin/php
<?php

	chdir(dirname(__FILE__));
	error_reporting(0);
	date_default_timezone_set('America/New_York');
	ini_set('default_socket_timeout', 15);
	$errors=0;
	$client="CHAOS";
	$base="BASES";
	$max_age=60*120;
	$cache_file="/tmp/cache-mirf-" . $client;
	$cache_dir="/tmp/cache-mirf-" . $client . "-files/";
	$store="/var/local/nrf24/";
	$binaries_dir=$store . "binaries/" . $client . "/";

	
	
$ceiling=50000;
$arduino_ceiling=255;


if (file_exists($cache_file)) {

// Output latest cache, no matter what.

$lines=file($cache_file);
foreach ($lines as $line_num => $line) {
echo $line;
usleep(50000);
}



if (time() - filemtime($cache_file) < $max_age) {

// If cache was fresh, let's quit.

exit;

}
else {
// echo "cache too old";
}

} else {
// echo "cache doesn't exist";
 }


echo $client . $base . "A\n" ;

$kardashian = file_get_contents("https://www.google.com/search?safe=off&hl=en&gl=us&authuser=0&biw=1237&bih=606&tbs=qdr%3Ad&tbm=nws&q=kardashian&oq=kardashian&gs_l=serp.3..0l8.84159.85111.0.85260.10.5.0.5.5.0.131.546.2j3.5.0.msedr...0...1c.1.59.serp..0.10.558.ATs1EBceKq0");
if (!$kardashian) {
	touch($cache_file);
	exit();
	
}

preg_match("/About [\d,]* results/",$kardashian, $matches_kardashian);
// echo $stats_kardashian[0] . "\n";
$stats_kardashian=preg_replace("/\D/","",$matches_kardashian[0]);
$value_kardashian=intval($stats_kardashian/$ceiling*$arduino_ceiling);
if ($value_kardashian > $arduino_ceiling) {
$value_kardashian=$arduino_ceiling;
}
 
sleep(32);

$unrest = file_get_contents("https://www.google.com/search?safe=off&hl=en&gl=us&authuser=0&biw=1237&bih=606&tbs=qdr%3Ad&tbm=nws&q=unrest&oq=unrest&gs_l=serp.3..0l8.84159.85111.0.85260.10.5.0.5.5.0.131.546.2j3.5.0.msedr...0...1c.1.59.serp..0.10.558.ATs1EBceKq0");
if (!$unrest) {
	touch($cache_file);
	exit();
	
}

preg_match("/About [\d,]* results/",$unrest, $matches_unrest);
// echo $matches_unrest[0] . "\n";

$stats_unrest=preg_replace("/\D/","",$matches_unrest[0]);

$value_unrest=intval($stats_unrest/$ceiling*$arduino_ceiling);
if ($value_unrest > $arduino_ceiling) {
$value_unrest=$arduino_ceiling;
}
 
sleep(19);


$unemployment = file_get_contents("https://www.google.com/search?safe=off&hl=en&gl=us&authuser=0&biw=1237&bih=606&tbs=qdr%3Ad&tbm=nws&q=unemployment&oq=unemployment&gs_l=serp.3..0l8.84159.85111.0.85260.10.5.0.5.5.0.131.546.2j3.5.0.msedr...0...1c.1.59.serp..0.10.558.ATs1EBceKq0");
if (!$unemployment) {
	touch($cache_file);
	exit();
	
}


preg_match("/About [\d,]* results/",$unemployment, $matches_unemployment);
// echo $matches_unemployment[0] . "\n";

$stats_unemployment=preg_replace("/\D/","",$matches_unemployment[0]);
$value_unemployment=intval($stats_unemployment/$ceiling*$arduino_ceiling);

if ($value_unemployment > $arduino_ceiling) {
$value_unemployment=$arduino_ceiling;
}
 



$string= $client . $base . "V" . sprintf("%03d", $value_unemployment) . sprintf("%03d", $value_unrest) . sprintf("%03d", $value_kardashian)  . "\n";
echo $string;

file_put_contents($cache_file,$string);





?>
